# This file was generated by GoReleaser. DO NOT EDIT.
cask "contemper" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b5ce0b13121423a574e235d7448dfbbb0c2586675fcfa53b6af66c9df8afd1fa"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc340d5e335ff342c83be0e90ebe6fd8a75ffdcb4b7a7d723153685678612f10"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "18b065ec418a1285378573aee97b961b16d83c4cc058418a29a589c49de52832"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "445d7a8f9d8f3adab512f8a511249bb819ebaf0c8529af24323d7a06f5835662"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_amd64.tar.gz"
    end
  end

  name "contemper"
  desc "Build bootable VM images from container images."
  homepage "https://contemper-project.github.io/contemper/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "e2fsprogs",
      "qemu",
    ]

  binary "contemper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contemper"]
    end
  end

  # No zap stanza required
end
