# This file was generated by GoReleaser. DO NOT EDIT.
cask "contemper" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "31efa5914331309a0f00287888ec7d0c6e7df54acc0de414aad2711085c4a4d8"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "01372e14bb2074f671f8905946c49cd068c3a977051204cf152c0d6592f70bfa"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4783dc58a4da0e7acce663e2aaebf58fada531670c1275d04f4c320a9677211c"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d562b413129e647d9bc8c8301b6a28019c299b9e2798b2393dd212488435df78"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_amd64.tar.gz"
    end
  end

  name "contemper"
  desc "Build bootable VM images from container images."
  homepage "https://contemper-project.github.io/contemper/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "e2fsprogs",
      "qemu",
    ]

  binary "contemper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contemper"]
    end
  end

  # No zap stanza required
end
