# This file was generated by GoReleaser. DO NOT EDIT.
cask "contemper" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/contemper"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f914ed46a6cd8eefe7eed4748d750e58885c427df5b73586222daf4a39d0e5d7"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e779d7fe28b1875c7be08c1c86e6347f6a409fdd13250c92e3fdc7dc8accc403"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f64afd4836fc371bb014b15d4f19517347770ff5bc0c0a1d11fe3b5b9c736959"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "718cfee5060be82317b89b06e9e5f2afd070dcafb1e75a6a3dbf89d0a1049d51"
      url "https://github.com/contemper-project/contemper/releases/download/v#{version}/contemper_#{version}_linux_amd64.tar.gz"
    end
  end

  name "contemper"
  desc "Build bootable VM images from container images."
  homepage "https://contemper-project.github.io/contemper/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "e2fsprogs",
      "qemu",
    ]

  binary "contemper"
  bash_completion "completions/contemper.bash"
  fish_completion "completions/contemper.fish"
  zsh_completion "completions/_contemper"

  # No zap stanza required
end
